---
pack: clean_queue_pack
ref: clean_queue_pack.clean_queue_rule
name: clean_queue_rule
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "clean_queue"
criteria:
  trigger.body.queue:
    type: exists
    pattern: {}
action:
  ref: clean_queue_pack.clean_queue_action.py
  description: Clean RabbitMQ queue
  parameters:
    queue: "{{trigger.body.queue}}"
